export enum TorrentSites {
    _1337x = "1337x",
    TorrentGalaxy = "tgx",
    Torlock = "torlock",
    PirateBay = "piratebay",
    Nyaasi = "nyaasi",
    Zooqle = "zooqle",
    KickAss = "kickass",
    Bitsearch = "bitsearch",
    MagnetDL = "magnetdl",
    Libgen = "libgen",
    YTS = "yts",
    Limetorrent = "limetorrent",
    TorrentFunk = "torrentfunk",
    Glodls = "glodls",
    TorrentProject = "torrentproject",
    YourBittorrent = "ybt",
}